AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post steps for route53 and basepathmapping

Parameters:
  DomainName:
    Type: String
  CloudFrontDistro:
    Type: String
  ZoneName:
    Type: String

Resources:
  AliasDNSEntry:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref CloudFrontDistro
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront zone id hardcoded by design
      HostedZoneName: !Ref ZoneName
      Name: !Ref DomainName
      Type: A
  AliasDNSEntry6:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref CloudFrontDistro
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront zone id hardcoded by design
      HostedZoneName: !Ref ZoneName
      Name: !Ref DomainName
      Type: AAAA

  NodeBasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      BasePath: node
      DomainName: !Ref DomainName
      RestApiId: !ImportValue NodeApiId
      Stage: prod
  PythonBasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      BasePath: python
      DomainName: !Ref DomainName
      RestApiId: !ImportValue PythonApiId
      Stage: prod

