AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post steps for route53 and basepathmapping

Parameters:
  DomainName:
    Type: String
  CloudFrontDistro:
    Type: String
  ZoneName:
    Type: String

Resources:
  ExampleDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref ZoneName
      Comment: DNS name for my distro
      Name: !Ref DomainName
      Type: CNAME
      TTL: '60'
      ResourceRecords:
      - !Ref CloudFrontDistro

  ExampleBasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !ImportValue RestApiId # cross stack ref with poor naming scheme
      Stage: prod

